# Generated by Django 5.2.8 on 2025-11-26 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gider Adı')),
                ('category', models.CharField(choices=[('RENT', 'Kira'), ('SALARY', 'Maaş'), ('RAW', 'Hammadde'), ('OTHER', 'Diğer')], max_length=10, verbose_name='Kategori')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ortak Adı')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kar Payı Yüzdesi (%)')),
                ('current_receivable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Alacak Bakiyesi')),
            ],
            options={
                'verbose_name': 'İş Ortağı',
                'verbose_name_plural': 'İş Ortakları',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Satış Fiyatı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Satışta mı?')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Kar')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='Ortaklara Dağıtıldı mı?')),
            ],
            options={
                'verbose_name': 'Kar Dağıtım Kaydı',
                'verbose_name_plural': 'Kar Dağıtım Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kurye Adı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kurye',
                'verbose_name_plural': 'Kuryeler',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bayi Adı/Unvanı')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='Vergi Numarası')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cari Bakiye')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bayi Cari Hesap',
                'verbose_name_plural': 'Bayi Cari Hesapları',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('method', models.CharField(choices=[('CASH', 'Nakit'), ('BANK', 'Banka Havalesi'), ('CARD', 'Kredi Kartı')], default='CASH', max_length=10, verbose_name='Ödeme Yöntemi')),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tahsilat Tarihi')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='management.dealer', verbose_name='Tahsilat Yapılan Bayi')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tahmini Toplam Tutar')),
                ('status', models.CharField(choices=[('NEW', 'Yeni Sipariş'), ('PREP', 'Hazırlanıyor'), ('DELIVERY', 'Teslimatta'), ('CONFIRMED', 'Teslim Edildi/Tamamlandı'), ('CANCELED', 'İptal Edildi')], default='NEW', max_length=10, verbose_name='Durum')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='management.dealer', verbose_name='Bayi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.PositiveIntegerField(verbose_name='Sipariş Edilen Miktar')),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sipariş Anındaki Birim Fiyat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, verbose_name='Teslim Edilen Miktar')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Teslimat Onaylandı mı?')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Teslimat Tarihi')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='management.courier', verbose_name='Kurye')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='management.orderitem', verbose_name='Sipariş Kalemi')),
            ],
            options={
                'verbose_name': 'Teslimat Kaydı',
                'verbose_name_plural': 'Teslimat Kayıtları',
            },
        ),
    ]
