# Generated by Django 5.2.8 on 2025-11-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_unit_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hammadde Adı')),
                ('unit', models.CharField(max_length=50, verbose_name='Ölçü Birimi (Kg, Lt, Adet vb.)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Alış Maliyeti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hammadde',
                'verbose_name_plural': 'Hammaddeler',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama/Hazırlık Notları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Reçete')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='management.product', verbose_name='Nihai Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Reçetesi',
                'verbose_name_plural': 'Ürün Reçeteleri',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Gerekli Miktar')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rawmaterial', verbose_name='Hammadde')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.recipe', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete Kalemi',
                'verbose_name_plural': 'Reçete Kalemleri',
                'unique_together': {('recipe', 'raw_material')},
            },
        ),
    ]
