# Generated by Django 5.2.8 on 2025-11-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rawmaterial_recipe_recipeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bayiye Özel Satış Fiyatı')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='management.dealer', verbose_name='Bayi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_prices', to='management.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Bayi Özel Fiyatı',
                'verbose_name_plural': 'Bayi Özel Fiyat Listeleri',
                'unique_together': {('dealer', 'product')},
            },
        ),
    ]
