# Generated by Django 5.2.8 on 2025-11-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_dealerprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordering_enabled', models.BooleanField(default=True, verbose_name='Bayi Sipariş Alımı Açık mı?')),
            ],
            options={
                'verbose_name': 'Global Sipariş Ayarı',
                'verbose_name_plural': 'Global Sipariş Ayarları',
            },
        ),
    ]
