# Generated by Django 5.2.8 on 2025-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_delivery_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Fiyat/Durum Kilitli'),
        ),
    ]
