# Generated by Django 5.2.8 on 2025-12-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_order_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBT', 'Borç (Satış/Fatura)'), ('CREDIT', 'Alacak (Tahsilat)')], max_length=10, verbose_name='Hareket Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_model', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='management.dealer', verbose_name='Bayi')),
            ],
            options={
                'verbose_name': 'Cari Hesap Hareketi',
                'verbose_name_plural': 'Cari Hesap Hareketleri',
            },
        ),
    ]
