# Generated by Django 5.2.8 on 2025-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fatura_numarasi',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Fatura Numarası'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Kilitli'),
        ),
    ]
