# Generated by Django 5.2.8 on 2025-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_order_fatura_numarasi_alter_order_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fatura_numarasi',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Fiyat/Durum Kilitli'),
        ),
    ]
