# Generated by Django 5.2.8 on 2025-12-02 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_order_fatura_numarasi_alter_order_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yeni Sipariş'), ('PREP', 'Hazırlanıyor'), ('DELIVERY', 'Teslimatta'), ('CONFIRMED', 'Teslim Edildi/Tamamlandı'), ('INVOICED', 'Faturalandırıldı'), ('CANCELED', 'İptal Edildi')], default='NEW', max_length=10, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Fatura Numarası')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fatura Tarihi')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nihai Tutar')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='management.dealer', verbose_name='Bayi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='management.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-invoice_date', 'invoice_number'],
            },
        ),
    ]
