# Generated by Django 5.2.8 on 2025-12-03 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_order_status_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_vat_included',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Satış Fiyatı (KDV Dahil)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), help_text='Örnek: %18 için 0.18, %10 için 0.10 giriniz.', max_digits=5, verbose_name='Satış KDV Oranı (Decimal)'),
        ),
    ]
