# Generated by Django 5.2.8 on 2025-12-03 08:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_product_price_vat_included_product_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Örnek: %20 için 0.20, %10 için 0.10 giriniz.', max_digits=5, verbose_name='Satış KDV Oranı (Decimal)'),
        ),
    ]
