# Generated by Django 5.2.8 on 2025-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_product_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=50, verbose_name='Kaynak Birim (Örn: kg)')),
                ('target_unit', models.CharField(max_length=50, verbose_name='Hedef Birim (Örn: gr)')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text="Örn: 1 kg'ı 1000 gr'a çevirmek için 1000 girin. 1 gr'ı 1 kg'a çevirmek için 0.001 girin.", max_digits=10, verbose_name='Çevrim Faktörü (Kaynak * Faktör = Hedef)')),
            ],
            options={
                'verbose_name': 'Birim Çevrimi',
                'verbose_name_plural': 'Birim Çevrimleri',
                'unique_together': {('source_unit', 'target_unit')},
            },
        ),
    ]
