# Generated by Django 5.2.8 on 2025-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_unitconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_unit',
            field=models.CharField(default='ADET', help_text='Miktarın girildiği birim (Örn: adet, koli, kg). Ürün biriminden farklı olabilir.', max_length=50, verbose_name='Sipariş Birimi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_at_order',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sipariş Anındaki Birim Fiyat (Ürün Ana Birimi Cinsinden)'),
        ),
    ]
