# Generated by Django 5.2.8 on 2025-12-03 14:38
import re
import django.db.models.deletion
from django.db import migrations, models

# ----------------------------------------------------
# KRİTİK: VERİ TAŞIMA FONKSİYONU
# ----------------------------------------------------
def forwards_func(apps, schema_editor):
    # Modelleri çek
    Unit = apps.get_model('management', 'Unit')
    Product = apps.get_model('management', 'Product')
    RawMaterial = apps.get_model('management', 'RawMaterial')
    OrderItem = apps.get_model('management', 'OrderItem')
    # KRİTİK EKLENTİ: UnitConversion modelini dahil et
    UnitConversion = apps.get_model('management', 'UnitConversion') 

    db_alias = schema_editor.connection.alias
    
    # 1. Eski birimleri TÜM İLGİLİ MODELLERDEN topla
    old_product_units = Product.objects.using(db_alias).values_list('unit', flat=True).distinct()
    old_rawmaterial_units = RawMaterial.objects.using(db_alias).values_list('unit', flat=True).distinct()
    old_orderitem_units = OrderItem.objects.using(db_alias).values_list('ordered_unit', flat=True).distinct()
    
    # KRİTİK EKLENTİ: UnitConversion'dan kaynak ve hedef birimleri topla
    old_uc_source_units = UnitConversion.objects.using(db_alias).values_list('source_unit', flat=True).distinct()
    old_uc_target_units = UnitConversion.objects.using(db_alias).values_list('target_unit', flat=True).distinct()

    # Tüm birimleri tek bir kümede birleştir
    all_old_units = set()
    for unit_list in [old_product_units, old_rawmaterial_units, old_orderitem_units, old_uc_source_units, old_uc_target_units]:
        for unit in unit_list:
            if unit: 
                all_old_units.add(unit)

    # 2. Yeni Unit kayıtlarını oluştur
    unit_map = {}
    for unit_name in all_old_units:
        unit, created = Unit.objects.using(db_alias).get_or_create(name=unit_name)
        unit_map[unit_name] = unit.pk
        
    # 3. Eski CharField'ları, QuerySet.update() ile yeni Unit ID'lerine güncelle
    for unit_name, unit_pk in unit_map.items():
        # Diğer modeller
        Product.objects.using(db_alias).filter(unit=unit_name).update(unit=unit_pk)
        RawMaterial.objects.using(db_alias).filter(unit=unit_name).update(unit=unit_pk)
        OrderItem.objects.using(db_alias).filter(ordered_unit=unit_name).update(ordered_unit=unit_pk)
        
        # KRİTİK DÜZELTME: UnitConversion alanlarını güncelle
        UnitConversion.objects.using(db_alias).filter(source_unit=unit_name).update(source_unit=unit_pk)
        UnitConversion.objects.using(db_alias).filter(target_unit=unit_name).update(target_unit=unit_pk)
# ----------------------------------------------------

class Migration(migrations.Migration):

    dependencies = [
        # KRİTİK: Bu kısmı, Sizin en sonki başarılı migration numaranızla değiştirin!
        ('management', '0014_unitconversion'), 
    ]

    operations = [
        # 1. Unit modelini oluştur (LookupError çözüldü)
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Birim Adı (Örn: kg, adet)')),
            ],
            options={
                'verbose_name': 'Tanımlı Birim',
                'verbose_name_plural': 'Tanımlı Birimler',
            },
        ),
        
        # 2. Veri taşıma fonksiyonunu çalıştır (Unit kayıtlarını dolduruldu)
        migrations.RunPython(forwards_func, migrations.RunPython.noop), 
        
        # 3. Alanları CharField'dan ForeignKey'e çevir (IntegrityError çözüldü)
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sipariş Edilen Miktar'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.unit', verbose_name='Sipariş Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.unit', verbose_name='Ana Birim'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.unit', verbose_name='Maliyet Birimi'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='source_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_conversions', to='management.unit', verbose_name='Kaynak Birim'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='target_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_conversions', to='management.unit', verbose_name='Hedef Birim'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('source_unit', 'target_unit')},
        ),
    ]