# Generated by Django 5.2.8 on 2025-12-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_orderitem_ordered_unit_and_more'),
        ('management', '0016_unit_alter_orderitem_ordered_quantity_and_more'),
    ]

    operations = [
    ]
