# Generated by Django 5.2.8 on 2025-12-03 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_merge_20251203_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.unit', verbose_name='Sipariş Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Satışta mı?'),
        ),
    ]
