# Generated by Django 5.2.8 on 2025-12-05 06:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_orderitem_ordered_unit_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'verbose_name': 'Kar Dağıtımı', 'verbose_name_plural': 'Kar Dağıtımları'},
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='is_distributed',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='start_date',
        ),
        migrations.AddField(
            model_name='partner',
            name='total_profit_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Alınan Toplam Kar Payı'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dağıtılan Kar Tutarı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='distribution_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dağıtım Tarihi'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='partner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.partner', verbose_name='Ortak'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Kar Payı Yüzdesi (%)'),
        ),
    ]
