# Generated by Django 5.2.8 on 2025-12-05 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_collection_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Tahsilat', 'verbose_name_plural': '04.Tahsilatlar'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Kurye', 'verbose_name_plural': '12.Kuryeler'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Bayi Hesap', 'verbose_name_plural': '02. Bayi Hesapları'},
        ),
        migrations.AlterModelOptions(
            name='dealerprice',
            options={'verbose_name': 'Bayi Özel Fiyatı', 'verbose_name_plural': '04.Bayi Satış Fiyat Tanımlama'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Teslimat Kaydı', 'verbose_name_plural': '12.Kurye Teslimat Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Gider', 'verbose_name_plural': '15.Giderler'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', 'invoice_number'], 'verbose_name': 'Fatura', 'verbose_name_plural': '14.Faturalar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': '10.Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderconfiguration',
            options={'verbose_name': 'Global Sipariş Ayarı', 'verbose_name_plural': '10.Sipariş Kontrol'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'İş Ortağı', 'verbose_name_plural': '16.İş Ortakları'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': '07.Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'verbose_name': 'Kar Dağıtımı', 'verbose_name_plural': '17.Kar Dağıtımları'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Hammadde', 'verbose_name_plural': '08.Hammaddeler'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Ürün Reçetesi', 'verbose_name_plural': '09.Ürün Reçeteleri'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Cari Hesap Hareketi', 'verbose_name_plural': '04. Hesap Hareketleri'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Tanımlı Birim', 'verbose_name_plural': '05.Birim Tanımları'},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'verbose_name': 'Birim Çevrimi', 'verbose_name_plural': '06.Birim Çevrimleri'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='management.dealer', verbose_name='Bayi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBT', 'Borç (Satış/Fatura)'), ('COLLECTION', 'Alacak (Tahsilat)')], max_length=10, verbose_name='Hareket Türü'),
        ),
    ]
