# Generated by Django 5.2.8 on 2025-12-05 23:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_collection_options_alter_courier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitdistribution',
            name='month',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=0, verbose_name='Ay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Yıl'),
        ),
        migrations.AlterUniqueTogether(
            name='profitdistribution',
            unique_together={('month', 'year')},
        ),     
                
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'verbose_name': 'Kâr Dağıtımı', 'verbose_name_plural': '90. Kâr Dağıtımı Yönetimi'},
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='is_distributed',
            field=models.BooleanField(default=False, verbose_name='Kâr Dağıtımı Yapıldı mı?'),
        ),
        
        migrations.AddField(
            model_name='profitdistribution',
            name='total_net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Toplam Net Kâr'),
        ),
        
        migrations.AlterField(
            model_name='profitdistribution',
            name='description',
            field=models.TextField(blank=True, default=0, verbose_name='Dağıtım Açıklaması'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='distribution_date',
        ),
        migrations.RemoveField(
            model_name='profitdistribution',
            name='partner',
        ),
    ]