# Generated by Django 5.2.8 on 2025-12-06 00:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_profitdistribution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Ortak', 'verbose_name_plural': '80. Ortaklar ve Oranları'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='current_receivable',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='share_percentage',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='total_profit_received',
        ),
        migrations.AddField(
            model_name='partner',
            name='distribution_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Dağıtım Oranı (%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='PartnerProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kullanılan Oran (%)')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Hesaplanan Tutar (TL)')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='management.profitdistribution', verbose_name='Kâr Dağıtım Kaydı')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.partner', verbose_name='Ortak')),
            ],
            options={
                'verbose_name': 'Ortak Kâr Payı',
                'verbose_name_plural': 'Ortak Kâr Payları',
                'unique_together': {('distribution', 'partner')},
            },
        ),
    ]
