# Generated by Django 5.2.8 on 2025-12-06 00:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='current_receivable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Alacak Bakiyesi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='eski', max_length=100, verbose_name='Ortak Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Kar Payı Yüzdesi (%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='total_profit_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Alınan Toplam Kar Payı'),
        ),
    ]
