# Generated by Django 5.2.8 on 2025-12-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_partner_current_receivable_partner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='İade Miktarı')),
                ('reason', models.TextField(verbose_name='İade Sebebi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='management.order', verbose_name='İlgili Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='İade Edilen Ürün')),
            ],
            options={
                'verbose_name': 'İade Talebi',
                'verbose_name_plural': 'İade Talepleri',
            },
        ),
    ]
