# Generated by Django 5.2.8 on 2026-01-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitdistribution',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Yıl'),
        ),
    ]
