# Generated by Django 5.2.8 on 2026-01-02 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_profitdistribution_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='method',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(default='Nakit', max_length=50, verbose_name='Tahsilat Türü'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
    ]
