# Generated by Django 5.2.8 on 2026-01-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_remove_collection_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='date',
        ),
        migrations.AddField(
            model_name='collection',
            name='method',
            field=models.CharField(choices=[('CASH', 'Nakit'), ('BANK', 'Banka Havalesi'), ('CARD', 'Kredi Kartı')], default='CASH', max_length=10, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cari Bakiye'),
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
