# Generated by Django 5.2.8 on 2026-01-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_collection_collection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='current_balance',
        ),
    ]
