# Generated by Django 5.2.8 on 2026-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_remove_dealer_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
    ]
