# Generated by Django 5.2.8 on 2026-01-04 19:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_order_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Tahsilat', 'verbose_name_plural': 'Tahsilatlar'},
        ),
        migrations.AlterModelOptions(
            name='dealerprice',
            options={'verbose_name': 'Bayi Özel Fiyatı', 'verbose_name_plural': 'Bayi Satış Fiyat Tanımlama'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Gider', 'verbose_name_plural': 'Giderler'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', 'invoice_number'], 'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturalar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Ortak', 'verbose_name_plural': 'Ortaklar ve Oranları'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='profitdistribution',
            options={'verbose_name': 'Kâr Dağıtımı', 'verbose_name_plural': 'Kâr Dağıtımı Yönetimi'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Hammadde', 'verbose_name_plural': 'Hammaddeler'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Ürün Reçetesi', 'verbose_name_plural': 'Ürün Reçeteleri'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Cari Hesap Hareketi', 'verbose_name_plural': 'Hesap Hareketleri'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='method',
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tahsilat Tutarı'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='management.dealer', verbose_name='Bayi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Örnek: %1 için 0.01, %10 için 0.10 giriniz.', max_digits=5, verbose_name='Satış KDV Oranı (Decimal)'),
        ),
    ]
