# Generated by Django 5.2.8 on 2026-01-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_collection_options_alter_dealerprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Kurye', 'verbose_name_plural': 'Kuryeler'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Bayi Hesap', 'verbose_name_plural': 'Bayi Hesapları'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBT', 'Borç (Satış/Fatura)'), ('Collection', 'Alacak (Tahsilat)')], max_length=10, verbose_name='Hareket Türü'),
        ),
    ]
