# Generated by Django 5.2.8 on 2026-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_courier_options_alter_dealer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yeni Sipariş'), ('PREP', 'Hazırlanıyor'), ('TESLİMATTA', 'Teslimatta'), ('CONFIRMED', 'Teslim Edildi/Tamamlandı'), ('INVOICED', 'Faturalandırıldı'), ('CANCELLED', 'İptal Edildi'), ('RETURNED', 'İade Edildi')], default='NEW', max_length=10, verbose_name='Durum'),
        ),
    ]
