# Generated by Django 5.2.8 on 2026-01-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='İade Tutarı')),
                ('reason', models.TextField(verbose_name='İade Nedeni')),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı (Bakiyeye İşlendi)'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='management.dealer', verbose_name='Bayi')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.order', verbose_name='İlgili Sipariş')),
            ],
            options={
                'verbose_name': 'İade Talebi',
                'verbose_name_plural': 'İade Talepleri',
            },
        ),
    ]
