# Generated by Django 5.2.8 on 2026-01-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='İade Adedi')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.orderitem', verbose_name='İade Edilen Ürün')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='management.returnrequest')),
            ],
            options={
                'verbose_name': 'İade Edilen Ürün',
                'verbose_name_plural': 'İade Edilen Ürünler',
            },
        ),
    ]
