# Generated by Django 5.2.8 on 2026-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_returnrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yeni Sipariş'), ('PREP', 'Hazırlanıyor'), ('TESLİMATTA', 'Teslimatta'), ('CONFIRMED', 'Teslim Edildi/Tamamlandı'), ('INVOICED', 'Faturalandırıldı'), ('CANCELLED', 'İptal Edildi')], default='NEW', max_length=10, verbose_name='Durum'),
        ),
    ]
