# Generated by Django 5.2.8 on 2026-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_transaction_description_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='İade Miktarı'),
        ),
    ]
