# Generated by Django 5.2.8 on 2026-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_alter_returnrequestitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Tahsilat', 'verbose_name_plural': 'Bayi Tahsilatlar'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Bayi Hesap', 'verbose_name_plural': 'Bayi Cari Hesapları'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Teslimat Kaydı', 'verbose_name_plural': 'Kurye Teslimat Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Gider', 'verbose_name_plural': 'Yönetim Giderler'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', 'invoice_number'], 'verbose_name': 'Fatura', 'verbose_name_plural': 'Bayi Faturalar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Bayi Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderconfiguration',
            options={'verbose_name': 'Global Sipariş Ayarı', 'verbose_name_plural': 'Bayi Sipariş Kontrol'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Ortak', 'verbose_name_plural': 'Yönetim Ortaklar'},
        ),
        migrations.AlterModelOptions(
            name='partnerprofitshare',
            options={'verbose_name': 'Ortak Kâr Payı', 'verbose_name_plural': 'Yönetim  Kâr Payı'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'Hammadde', 'verbose_name_plural': 'Üretim Hammade'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Ürün Reçetesi', 'verbose_name_plural': 'Üretim Reçeteleri'},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'verbose_name': 'İade Talebi', 'verbose_name_plural': 'Bayi İade Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Cari Hesap Hareketi', 'verbose_name_plural': 'Bayi Hesap Hareketleri'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Tanımlı Birim', 'verbose_name_plural': 'Ürün Birim Tanımları'},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'verbose_name': 'Birim Çevrimi', 'verbose_name_plural': 'Ürün Birim Çevrimleri'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBT', 'Borç (Satış/Fatura)'), ('Collection', 'Alacak (Tahsilat)'), ('RETURN', 'İade (Bakiye Güncelleme)')], max_length=10, verbose_name='Hareket Türü'),
        ),
    ]
