# Generated by Django 5.2.8 on 2026-01-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_collection_options_alter_dealer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBT', 'Borç (Satış/Fatura)'), ('COLLECTION', 'Alacak (Tahsilat)'), ('RETURN', 'İade (Bakiye Güncelleme)')], max_length=10, verbose_name='Hareket Türü'),
        ),
    ]
