# Generated by Django 5.2.8 on 2026-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBT', 'Borç (Bayi Satış/Fatura)'), ('COLLECTION', 'Bayi Alacak (Tahsilat)'), ('RETURN', 'İade (Bakiye Güncelleme)')], max_length=10, verbose_name='Hareket Türü'),
        ),
    ]
