# Generated by Django 5.2.8 on 2026-01-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
