# Generated by Django 5.2.8 on 2026-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_orderitem_delivered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_at_order',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Sipariş Anındaki Birim Fiyat (Ürün Ana Birimi Cinsinden)'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gerekli Miktar'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, help_text="Örn: 1 kg'ı 1000 gr'a çevirmek için 1000 girin. 1 gr'ı 1 kg'a çevirmek için 0.001 girin.", max_digits=10, verbose_name='Çevrim Faktörü (Kaynak * Faktör = Hedef)'),
        ),
    ]
