"""
Django settings for b2b project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=zzak%@j@+ipc^np7&=eu*j#kz#fc11#n#r!2ag+%i!i=+sp7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['djangomurat.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'management.apps.ManagementConfig',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'karabulutayintap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'karabulutayintap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True # Yerelleştirmeyi (Localization) etkinleştir

USE_TZ = True

# Kısa tarih/saat formatı
DATETIME_FORMAT = 'd.m.Y H:i'
# Örnek: 02.12.2025 13:09 (24 saat formatı)

# Binlik ayırıcıyı etkinleştir (Sayıların 1000'lik gruplara ayrılmasını sağlar)
USE_THOUSAND_SEPARATOR = True 

# Binlik ayırıcı karakteri: Türkçe formatta nokta (.) olmalı.
THOUSAND_SEPARATOR = '.' 

# Ondalık ayırıcı karakteri: Türkçe formatta virgül (,) olmalı.
DECIMAL_SEPARATOR = ',' 

# Ondalık kısımda gösterilecek maksimum hane sayısı
# (Paralar için 2 hane standarttır)
NUMBER_GROUPING = 3 # Sayıları 3'erli gruplara ayır

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Dosyaların toplanacağı yer

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------------------------
# DJANGO ADMIN BAŞLIK VE SİTE AYARLARI
# ----------------------------------------------------------------------

# Yönetim paneli HTML <title> etiketi (tarayıcı sekme başlığı)
ADMIN_TITLE = "Pastane Yönetimi | Yönetici Paneli"

# Yönetim paneli üst kısım başlığı (Header'daki ana başlık)
ADMIN_SITE_HEADER = "Pastane Yönetimi"

# Yönetim paneli ana sayfa başlığı (Admin index sayfasının başlığı)
ADMIN_INDEX_TITLE = "Pastane Yönetimi Kontrol Paneli"

# Başarılı girişten sonra kullanıcıyı nereye yönlendireceğimizi belirtir.
# Bu, /accounts/profile/ varsayılanını geçersiz kılar.
LOGIN_REDIRECT_URL = '/dashboard/' 

# Not: Eğer logout yapıldığında ana sayfaya yönlendirmek isterseniz:
LOGOUT_REDIRECT_URL = '/'

STATICFILES_DIRS = [BASE_DIR / "static"]